### ISSUE TITLE
Can I program a custom MIDI input driver with Moony?

### ISSUE THREAD

**Issue by unfa** [OpenMusicKontrollers/moony.lv2#1]
I wonder if I can use Moony to cleverly route manipulate my CC input to use two MIDI-CC buttons to increase/decrease output MIDI channel?

I'm looking for plugins that can do this, but I can see anything, there's  bunch of great plugins that can convert notes to CC and vice versa, remap stuff, but Moony seems like the tool I need to do it in a n elegant way.

I Basically need to take MIDI input, use two MIDI CCs as special controls to increase/decrease an Int between 1 and 16, and pass everything through, altering the MIDI channel of the messages to use the selected channel.

How can I learn to do this stuff?

Are there any resources that I can use to learn how Moony works and how to program such stuff in LUA?

PS: I've noticed Moony has "C" and "A" input types. I thought it's about Control and Audio, but it's Control and Atom. I know Ardour has audio plugins written in LUA.

Is it possible manipulate standard MIDI messages at all with Moony? Or t is only intended as an internal tool for Synthpod? Is it possible to make a MIDI variant aswell?

**Comment by ventosus** [comment]
> How can I learn to do this stuff?

* There's the reference one can consult [1]
* There's an introductory talk from this years LAC [2] (I guess I should links that to moony's web presence)
* There's a dozen or so presets/templates shipping with moony

[1] https://openmusickontrollers.gitlab.io/moony.lv2/
[2] https://www.youtube.com/watch?v=JdnQcSQiW7Q&list=PLpEMKw8jHgdRA3ydjZvt73q4Nc4W0jvuz&index=30

**Comment by ventosus** [comment]
> Is it possible manipulate standard MIDI messages at all with Moony? Or t is only intended as an internal tool for Synthpod? Is it possible to make a MIDI variant aswell?
LV2 knows 4 types of ports:
1. Control port (your average knob value)
2. Audio port
3. CV port
4. Atom event sequence port

All event data in LV2 goes through atom ports. MIDI is just a special type of LV2 atom. Moony can handle arbitrary types of atoms, MIDI included.

**Comment by ventosus** [comment]
> I Basically need to take MIDI input, use two MIDI CCs as special controls to increase/decrease an Int between 1 and 16, and pass everything through, altering the MIDI channel of the messages to use the selected channel.

Sure, moony has been developed to be able to do such mappings.

I'll try to quickly prototype something that should get you going, stay tuned...

**Comment by ventosus** [comment]
Here a bare minimum that should do what you want (without handling all the nasty corner cases)

[Moony_A1_x_A1_unfa_midi_sprinkler.preset.lv2.zip](https://github.com/OpenMusicKontrollers/moony.lv2/files/1399979/Moony_A1_x_A1_unfa_midi_sprinkler.preset.lv2.zip)

**Comment by ventosus** [comment]
> Or t is only intended as an internal tool for Synthpod?

Not at all. moony runs in any LV2 host, or as single JACK app when loaded into jalv.

**Comment by ventosus** [comment]
First thing to learn about Lua is to not write it in CAPITALS [1], serious Lua developers may not even talk back to you ;)

[1] https://www.lua.org/about.html

**Comment by ventosus** [comment]
>  program such stuff in LUA?
If you're generally interested in Lua (it is used as scripting language in many audio apps), there's a book (take fourth edition for latest Lua which moony is based on) I can warmly recommend [1].

[1] https://www.lua.org/pil/

**Comment by unfa** [comment]
Wow. Thank you so much! You've confirmed to me that Moony is the tool for the job, and you've provided all help I could ask for :) I'll investigate the code you've prepared for me and see if I can use it and hack it to suit my live performance needs.
I must say that being able to manipulate MIDI events withing a plugin, with a simple scripting language is something I never even dreamed of - I always thought I'll have to code my own LV2 plugins for that or run some strange MIDI processing programs - but with this I can keep all that contained within a single Carla plugin host project and keep it elegant.  I'm really excited about your work - the tools you're crafting are unique and very powerful.

**Comment by ventosus** [comment]
Very much appreciated.

**Comment by unfa** [comment]
I'm trying to use the code you wrote but I haven't been able to get it to work so far. It doesn't forward the messages. As I understand it has a MIDI responder that checks the Controller how can I define an arbitrary CC number (or better: how can I use Sherlock to sample what I need to set as triggers) - can I use Sherlock to find that out?

**Comment by unfa** [comment]
Ok, I've figured out I can use Sherlock to find out event names that Moony will use for Inc/Dec operations. I've watched half of your LAC talk so far, as I don't want to understand sequencing, because that's too much for me right now, I first want to get the hang of simple manipulation of events.

BTW: Can I use the Controllers tab to have a nice preview of what is my active instrument?
Can I display the Cur value there somehow?

**Comment by unfa** [comment]
I used prints to identify what parts of the code execute, and the function `run` works, but the function `controller` is never called.

**Comment by ventosus** [comment]
which host do you use?

Oldish versions of e.g. carla didn't support multiple atom ports, so would never receive any MIDI.

To test if you receive any MIDI try the following code:

    function run(n, control, notify, seq, forge)
        for frames, atom in seq:foreach() do
            print(frames, atom)
        end
    end

This should print something in the log window when receiving e.g. MIDI

**Comment by ventosus** [comment]
Output in log window should look like:

    0 (chunk: 0x7f547c0069e0)

**Comment by unfa** [comment]
That's probably it. I have nothing. I use carla-git KXStudio package (version 2:1.9.7+git20170828v5).

**Comment by ventosus** [comment]
That should be new enough to work, will try to reproduce in carla here

**Comment by ventosus** [comment]
Can confirm, carla-git has the same problem again, gets confused with multiple atom ports and probably does not know where to send MIDI, to, best tell @falktk, so he can fix it again...

Works in any other host, though (qtractor, jalv, ardour, synthpod)

**Comment by unfa** [comment]
I have run it in jalv and it works. I guess I'll use jalv and make myself a script to run it before Carla to have it as a part of the chain.

**Comment by falkTX** [comment]
does this apply to the latest stable release of moony?
I have 0.22.0 installed here.

**Comment by unfa** [comment]
I have package  moony.lv2 in version 0.22.0-1kxstudio1.

**Comment by ventosus** [comment]
@falkTX thanks for chiming in

**Comment by unfa** [comment]
Here's what I crafted so far:
[Live.tar.gz](https://github.com/OpenMusicKontrollers/moony.lv2/files/1403221/Live.tar.gz)

The bash script `run.sh` loads Moony in jalv, then loads Carla. I've modified the code so it ignores events with `val = 0`, because I had everything working with double steps, instead of single.

It works! Now I can prepare myself more patches, wire them up in Carla to specific MIDI ports after MIDI splitter and I'm ready to go jam with a band.

**Comment by ventosus** [comment]
> It works! Now I can prepare myself more patches, wire them up in Carla to specific MIDI ports after MIDI splitter and I'm ready to go jam with a band.

;)

> BTW: Can I use the Controllers tab to have a nice preview of what is my active instrument?
Can I display the cur value there somehow?

Yes you can with the StateResponder [1] (which can be a bit tricky to use...)

[1] https://openmusickontrollers.gitlab.io/moony.lv2/#responder-state

**Comment by unfa** [comment]
Wow, so there are more options than just knob widgets? I guess a simple number display would do just fine. I'll keep a note of what instrument is where or just memorize it. I'm starting to read through he docs. Thanks!

**Comment by ventosus** [comment]
> Wow, so there are more options than just knob widgets?

Load the preset "State: Responder" and you'll see them all

**Comment by unfa** [comment]
I loaded it, but I get an error. Can't tell why, though, because it looks fine to me.
![selection_065](https://user-images.githubusercontent.com/491704/31841814-8185795e-b5eb-11e7-9a80-c3501124c083.png)

**Comment by ventosus** [comment]
What is at line 39?
