### ISSUE TITLE
Plugin freezes when parameter drop down is opened and then loses focus

### ISSUE THREAD

**Issue by SpotlightKid** [OpenMusicKontrollers/moony.lv2#15]
This seems to happen only under certain circumstances, e.g. when the drop down is very narrow and you then either change the focus to another window or click on another UI element in Moony. The whole UI then freezes and the CPU usages spikes and Moony can only be killed.

Please let me know, if you are not able to reproduce it and I'll try to narrow down the circumstances when this happens.

**Comment by ventosus** [comment]
Thanks for reporting, can reproduce this.

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/9>
