### ISSUE TITLE
compiling on OSX

### ISSUE THREAD

**Issue by lokkiikkol** [OpenMusicKontrollers/moony.lv2#17]
hi when trying to compile moony on OS X 10.15.7, i get the following error:

`[2/141] Compiling C object subprojects/d2tk/test.core.p/src_hash.c.o
In file included from ../subprojects/d2tk/src/hash.c:23:
../subprojects/d2tk/src/mum.h:230:24: warning: unknown attribute '__optimize__' ignored [-Wunknown-attributes]
static inline uint64_t _MUM_OPTIMIZE("unroll-loops")
                       ^
../subprojects/d2tk/src/mum.h:62:44: note: expanded from macro '_MUM_OPTIMIZE'
#define _MUM_OPTIMIZE(opts) __attribute__((__optimize__ (opts)))
                                           ^
../subprojects/d2tk/src/mum.h:334:13: warning: unsupported 'inline-all-stringops' in the 'target' attribute string; 'target' attribute ignored [-Wignored-attributes]
_MUM_TARGET("inline-all-stringops")
            ^
2 warnings generated.
[28/141] Compiling C object subprojects/d2tk/test.core.p/src_base_pty.c.o
FAILED: subprojects/d2tk/test.core.p/src_base_pty.c.o 
cc -Isubprojects/d2tk/test.core.p -Isubprojects/d2tk -I../subprojects/d2tk -I../subprojects/d2tk/pugl/include -I../subprojects/d2tk/nanovg/src -I../subprojects/d2tk/linenoise -I/usr/local/Cellar/libvterm/0.1.4/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu11 -O3 -D_GNU_SOURCE -fvisibility=hidden -ffast-math -MD -MQ subprojects/d2tk/test.core.p/src_base_pty.c.o -MF subprojects/d2tk/test.core.p/src_base_pty.c.o.d -o subprojects/d2tk/test.core.p/src_base_pty.c.o -c ../subprojects/d2tk/src/base_pty.c
../subprojects/d2tk/src/base_pty.c:243:5: error: implicit declaration of function 'ioctl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if(ioctl(vpty->fd, TIOCSWINSZ, &winsize) == -1)
           ^
../subprojects/d2tk/src/base_pty.c:320:2: error: implicit declaration of function 'execvpe' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        execvpe(argv[0], argv, envp);
        ^
../subprojects/d2tk/src/base_pty.c:337:58: warning: passing 'const struct termios *' to parameter of type 'struct termios *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if(openpty(&clone_data.master, &clone_data.slave, name, termp, winp) == -1)
                                                                ^~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/util.h:94:51: note: passing argument to parameter here
int     openpty(int *, int *, char *, struct termios *,
                                                      ^
../subprojects/d2tk/src/base_pty.c:337:65: warning: passing 'const struct winsize *' to parameter of type 'struct winsize *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        if(openpty(&clone_data.master, &clone_data.slave, name, termp, winp) == -1)
                                                                       ^~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/util.h:95:24: note: passing argument to parameter here
                     struct winsize *);
                                     ^
2 warnings and 2 errors generated.
[31/141] Compiling C object subprojects/d2tk/test.core.p/src_base_lineedit.c.o
ninja: build stopped: subcommand failed.
`

this is after i changed pty.h to util.h as suggested here: https://github.com/deadpixi/mtm/issues/6 in base_pty.h

**Comment by ventosus** [comment]
thanks for reporting

quote from the webpage:

> We only support free/libre platforms, please do not bother us with support requests for proprietary platforms.

sorry, but you're on your own here

[1] https://open-music-kontrollers.ch/

**Comment by lokkiikkol** [comment]
Ah ok, well that's a shame, but I understand. Been there.
