### ISSUE TITLE
global 'foreach' is not callable

### ISSUE THREAD

**Issue by ShantySuffisance** [OpenMusicKontrollers/moony.lv2#18]
Dear Hanspeter Portner, 
I wanted to try moony.lv2 with the following example but got an error (`global 'foreach' is not callable (a nil value)` ) in line 13 (the one with `seq|foreach()` ), that i do not understand. 
```
-- https://github.com/OpenMusicKontrollers/moony.lv2
-- (40:18)
-- Workshop Session 4: 7. Moony - rapid prototyping of LV2 (MIDI) event filters in Lua
local midiR = MIDIResponder({
  [MIDI.NoteOn] = function(self, frames, forge, channel, note, vel)
    forge:time(frames):midi(MIDI.NoteOn | channel, note, vel)
  end,
  [MIDI.NoteOff] = function(self, frames, forge, channel, note, vel)
    forge:time(frames):midi(MIDI.NoteOff | channel, note, vel)
  end
})
function run(n, control, notify, seq, forge)
  for frames, atom in seq|foreach() do
    midiR(frames, forge, atom)
  end
end
```
I don't know if it is related but when i compiled moony.lv2 yesterday there were some warnings and i got an error in the testlog.txt after i called `ninja test` : 

```
==================================== 7/8 =====================================
test:         moony.lv2 / LV2 lint
start time:   19:35:57
duration:     1.42s
result:       (exit status 139 or signal 11 SIGSEGV)
command:      MALLOC_PERTURB_=20 /usr/local/bin/lv2lint -I /home/bloemle/moony.lv2/build/ 'http://open-music-kontrollers.ch/lv2/moony#a1xa1' 'http://open-music-kontrollers.ch/lv2/moony#a2xa2' 'http://open-music-kontrollers.ch/lv2/moony#a4xa4' 'http://open-music-kontrollers.ch/lv2/moony#c1a1xc1a1' 'http://open-music-kontrollers.ch/lv2/moony#c1xc1' 'http://open-music-kontrollers.ch/lv2/moony#c2a1xc2a1' 'http://open-music-kontrollers.ch/lv2/moony#c2xc2' 'http://open-music-kontrollers.ch/lv2/moony#c4a1xc4a1' 'http://open-music-kontrollers.ch/lv2/moony#c4xc4'
----------------------------------- stderr -----------------------------------
Segmentation fault (core dumped)
============================================================================== 
```
Did i make an obvious error? Thank you very much for your great open source plugins!

**Comment by ventosus** [comment]
On 19.08.22 19:37, ShantySuffisance wrote:
> Dear Hanspeter Portner,

Hi there,

> I wanted to try moony.lv2 with the following example but got an error (|global
> 'foreach' is not callable (a nil value)| ) in line 13 (the one with
> |seq|foreach()| ), that i do not understand.

That should be a ':', not a '|', the latter is not a valid syntax.

    for frames, atom in seq:foreach() do
      -- ...
    done

> |-- https://github.com/OpenMusicKontrollers/moony.lv2 -- (40:18) -- Workshop
> Session 4: 7. Moony - rapid prototyping of LV2 (MIDI) event filters in Lua local
> midiR = MIDIResponder({ [MIDI.NoteOn] = function(self, frames, forge, channel,
> note, vel) forge:time(frames):midi(MIDI.NoteOn | channel, note, vel) end,
> [MIDI.NoteOff] = function(self, frames, forge, channel, note, vel)
> forge:time(frames):midi(MIDI.NoteOff | channel, note, vel) end }) function
> run(n, control, notify, seq, forge) for frames, atom in seq|foreach() do
> midiR(frames, forge, atom) end end |
>
> I don't know if it is related but when i compiled moony.lv2 yesterday there were
> some warnings and i got an error in the testlog.txt after i called |ninja test| :

Not related.

> |==================================== 7/8 =====================================
> test: moony.lv2 / LV2 lint start time: 19:35:57 duration: 1.42s result: (exit
> status 139 or signal 11 SIGSEGV) command: MALLOC_PERTURB_=20
> /usr/local/bin/lv2lint -I /home/bloemle/moony.lv2/build/
> 'http://open-music-kontrollers.ch/lv2/moony#a1xa1'
> 'http://open-music-kontrollers.ch/lv2/moony#a2xa2'
> 'http://open-music-kontrollers.ch/lv2/moony#a4xa4'
> 'http://open-music-kontrollers.ch/lv2/moony#c1a1xc1a1'
> 'http://open-music-kontrollers.ch/lv2/moony#c1xc1'
> 'http://open-music-kontrollers.ch/lv2/moony#c2a1xc2a1'
> 'http://open-music-kontrollers.ch/lv2/moony#c2xc2'
> 'http://open-music-kontrollers.ch/lv2/moony#c4a1xc4a1'
> 'http://open-music-kontrollers.ch/lv2/moony#c4xc4'
> ----------------------------------- stderr -----------------------------------
> Segmentation fault (core dumped)
> ============================================================================== |
>
> Did i make an obvious error? Thank you very much for your great open source plugins!

Tests run fine on my side.

What version of lv2lint do you use?

    lv2lint -v

**Comment by ShantySuffisance** [comment]
thank you very much for your response. 

with the typing error corrected, there are no errors anymore. But the test script still fails to let any midi note on / off through. 

Checking the version with `lv2lint -v` : 

```
$ lv2lint -v
Segmentation fault (core dumped)
```
the last line of `man lv2lint` says `Jan 15, 2021`

**Comment by ventosus** [comment]
Your code is fine, I've testet it here, NoteOn/Off go through just fine.

What is your setup (host, etc.). Put some 'print()' in your code to test if anything's coming in.

Well, something with your lv2lint on your system is terribly borked if it already crashes so early ;-)

**Comment by ShantySuffisance** [comment]
i just tried to compile lv2lint from source but meson cant find every required program and i just again end with "Segmentation fault".  

setup: Ubuntu 18.04.6 LTS x86_64 on an (really old) AMD Athlon 64 X2 Dual 5200+ (2) @ 2.700GHz. Host: Carla v2.5.0 on jackdmp v1.9.12. 

i'll give up now :/ . I'll try moony again, when i have a more modern cpu with a more modern OS. Thank you very much! I will close this issue as completed; my typing error was found :D

**Comment by ventosus** [comment]
lv2lint is only needed for the unit tests, if it does not run on your side, just remove/uninstall it. Moony does not need it to run.

**Comment by ventosus** [comment]
On 19.08.22 19:37, ShantySuffisance wrote:
> Dear Hanspeter Portner,

Hi there,

> I wanted to try moony.lv2 with the following example but got an error (|global
> 'foreach' is not callable (a nil value)| ) in line 13 (the one with
> |seq|foreach()| ), that i do not understand.

That should be a ':', not a '|', the latter is not a valid syntax.

    for frames, atom in seq:foreach() do
      -- ...
    done

> |-- https://github.com/OpenMusicKontrollers/moony.lv2 -- (40:18) -- Workshop
> Session 4: 7. Moony - rapid prototyping of LV2 (MIDI) event filters in Lua local
> midiR = MIDIResponder({ [MIDI.NoteOn] = function(self, frames, forge, channel,
> note, vel) forge:time(frames):midi(MIDI.NoteOn | channel, note, vel) end,
> [MIDI.NoteOff] = function(self, frames, forge, channel, note, vel)
> forge:time(frames):midi(MIDI.NoteOff | channel, note, vel) end }) function
> run(n, control, notify, seq, forge) for frames, atom in seq|foreach() do
> midiR(frames, forge, atom) end end |
> 
> I don't know if it is related but when i compiled moony.lv2 yesterday there were
> some warnings and i got an error in the testlog.txt after i called |ninja test| :

Not related.

> |==================================== 7/8 =====================================
> test: moony.lv2 / LV2 lint start time: 19:35:57 duration: 1.42s result: (exit
> status 139 or signal 11 SIGSEGV) command: MALLOC_PERTURB_=20
> /usr/local/bin/lv2lint -I /home/bloemle/moony.lv2/build/
> 'http://open-music-kontrollers.ch/lv2/moony#a1xa1'
> 'http://open-music-kontrollers.ch/lv2/moony#a2xa2'
> 'http://open-music-kontrollers.ch/lv2/moony#a4xa4'
> 'http://open-music-kontrollers.ch/lv2/moony#c1a1xc1a1'
> 'http://open-music-kontrollers.ch/lv2/moony#c1xc1'
> 'http://open-music-kontrollers.ch/lv2/moony#c2a1xc2a1'
> 'http://open-music-kontrollers.ch/lv2/moony#c2xc2'
> 'http://open-music-kontrollers.ch/lv2/moony#c4a1xc4a1'
> 'http://open-music-kontrollers.ch/lv2/moony#c4xc4'
> ----------------------------------- stderr -----------------------------------
> Segmentation fault (core dumped)
> ============================================================================== |
> 
> Did i make an obvious error? Thank you very much for your great open source plugins!

Tests run fine on my side.

What version of lv2lint do you use?

    lv2lint -v
