### ISSUE TITLE
Can't Copy+Paste

### ISSUE THREAD

**Issue by unfa** [OpenMusicKontrollers/moony.lv2#2]
Moony seems to read from system clipboard, but it's not doing any writes to it.
Using the "Middle mouse buffer" also doesn't work.

**Comment by ventosus** [comment]
'Middle mouse' is not implemented and most probably won't ever.

When editor is active, following shortcuts should work. cut and copy need a selection to do anything.

C-x: cut
C-c: copy
C-v: paste

Works as intended here.

Are you running some helper daemon that arbitrates between different X11 clipboards?

**Comment by unfa** [comment]
Interesting. I have KDE5, there's a KDE Clipboard manager program running, but I never had any issues with so far.

**Comment by unfa** [comment]
Strange, now it works! I'll close this for now, will resurrect if I find a legitimate problem here.

**Comment by ventosus** [comment]
Some hosts (e.g. ardour) do some fancy window embedding and can eat away keystrokes. Maybe something similar is going on here.
