### ISSUE TITLE
Using Tab key to indentate selection?

### ISSUE THREAD

**Issue by unfa** [OpenMusicKontrollers/moony.lv2#3]
Right now selecting a bunch of text and pressing tab will replace the selection with a single tab character, which is not what I intended.

In Kate (KDE plaintext editor) one can select a bunch of text and hit Tab to add preceeding tab characters to all lines selected. Shift+Tab removes one level of indentation.

I think that's very convenient.

**Comment by ventosus** [comment]
moony uses the nuklear toolkit [1], which ships only this  simple editor. As text editor preference is really individual, I won't add any special features to resemble another editor.

But, it is on the TODO list that one can edit code directly in ones favorite editor instead of using moony's editor. This should then make everyone happy.

[1] https://github.com/vurtun/nuklear

**Comment by unfa** [comment]
I see. Would using external editor mean that Moony will automatically re-read a Lua file from disk, that the user can edit with editor of his choice?

**Comment by ventosus** [comment]
> I see. Would using external editor mean that Moony will automatically re-read a Lua file from disk, that the user can edit with editor of his choice?

Exactly, code would be executed upon each file save

**Comment by ventosus** [comment]
external editor is available as of https://github.com/OpenMusicKontrollers/moony.lv2/commit/d0c3e28ad3abe961b09db501c58e0d7be65174c2

There's a caveat: Although built-in, it is disabled by default for now. LV2 (theoretically) supports multiple UIs per plugin instance. Moony's external editor support for now is implemented as an alternative UI. Most hosts (but latest synthpod) do not support multiple UIs, e.g. they will just use the first supported one. So, if a plugin defines multiple UIs, some hosts may show the first, others the second, ...

Latest synthpod lists them all and the user can choose which one to use.

You can already test this though, by modifying '/usr/lib/lv2/moony.lv2/manifest.ttl'

For the plugin of choice, simply (de)comment the wanted ui:

    moony:a1xa1
    	a lv2:Plugin ;
	lv2:minorVersion @MOONY_MINOR_VERSION@ ;
	lv2:microVersion @MOONY_MICRO_VERSION@ ;
	lv2:binary <moony@CMAKE_SHARED_MODULE_SUFFIX@> ;
	#ui:ui moony:moony_ui ;
	#ui:ui moony:moony_zimple_ui ;
	ui:ui moony:moony_zimple_kx ;
        rdfs:seeAlso <moony.ttl> .

The external UI expects the user to set an environment variable to hint which editor to load. If no environment variable is found, it'll fall back to use vi in xterm.

e.g. for your kate you'd do:

    export MOONY_EDITOR='kate'
    ardour|qtractor  ...

An alternative approach would be to start the external editor from within the default UI, but this would be cubersome to use.

Will have to open issues on all hosts for them to add support for multiple UIs (and then wait some years until it'll land in downstream)
