### ISSUE TITLE
Feature request: in File browser, double clicking directories/files to open/load them

### ISSUE THREAD

**Issue by milkmiruku** [OpenMusicKontrollers/moony.lv2#7]
Currently, to open a directory in the File Browser, one needs to click on it with the mouse then press the Return key or press the OK button to enter the directory.

It would be handy to be able to use the mouse for both entering directories and opening files.

(wee bug aside; on double clicking a File browser entry currently, the background colour becomes the colour of an unselected file)

**Comment by ventosus** [comment]
The nuklear toolkit has no double-click support, that's why you see strange bahaviour.

Single-click activation is possible, though.

**Comment by ventosus** [comment]
To make this less painful, I've come up with this 'solution' for now:

* single-click directory-change
* single-click file-loading
* poor-man's double-click file-loading (e.g. if you click the same file entry twice, it'll get loaded)

in 743e77e9c1042b1d34209d52eef1e1dd06bd67ca
