### ISSUE TITLE
Undo doesn't persisist after clicking Send

### ISSUE THREAD

**Issue by mxmilkb** [OpenMusicKontrollers/moony.lv2#9]
This makes undoing a breaking change impossible.

**Comment by ventosus** [comment]
Can reproduce that.

To circumvent for now, just use the keyboard shortcut: 'Shift-Enter' to send, that will preserve history.

**Comment by ventosus** [comment]
btw, every button has a keyboard shortcut, just hover with Ctrl pressed to view the corresponding tooltip

**Comment by ventosus** [comment]
This is a bug in the nuklear toolkit, needs to be fixed upstream

**Comment by ventosus** [comment]
fixed in 83d21d53f1a161278beb71698470468e824908ba

please test
